---
  - name: Install required software
    apt: name={{ item }} state=present
    with_items:
      - bridge-utils
      - resolvconf
      - ifenslave
      - iproute2

  - name: Configure routing tables
    template: src=rt_tables.j2 dest=/etc/iproute2/rt_tables owner=root group=root mode=0644
    when:
      - "'netconf' in hostvars[inventory_hostname]"
      - "'rt' in hostvars[inventory_hostname]['netconf']"

  - name: Configure normal interfaces
    template: src=if.j2 dest=/etc/network/interfaces.d/{{ item.key }} owner=root group=root mode=0644
    with_dict: "{{ hostvars[inventory_hostname]['netconf']['if'] }}"
    when:
      - "'netconf' in hostvars[inventory_hostname]"
      - "'if' in hostvars[inventory_hostname]['netconf']"

  - name: Configure bond interfaces
    template: src=bond.j2 dest=/etc/network/interfaces.d/{{ item.key }} owner=root group=root mode=0644
    with_dict: "{{ hostvars[inventory_hostname]['netconf']['bond'] }}"
    when:
      - "'netconf' in hostvars[inventory_hostname]"
      - "'bond' in hostvars[inventory_hostname]['netconf']"

  - name: Configure vlan interfaces
    template: src=vlan.j2 dest=/etc/network/interfaces.d/zz-{{ item.value.parent }}.{{ item.key }} owner=root group=root mode=0644
    with_dict: "{{ hostvars[inventory_hostname]['netconf']['vlan'] }}"
    when:
      - "'netconf' in hostvars[inventory_hostname]"
      - "'vlan' in hostvars[inventory_hostname]['netconf']"

  - name: Overwrite main network config file
    template: src=interfaces.j2 dest=/etc/network/interfaces owner=root group=root mode=0644
    when:
      - "'netconf' in hostvars[inventory_hostname]"
